// Import the PrismaClient class from our installed package
const { PrismaClient } = require('@prisma/client');

// To prevent creating multiple connection pools during development due to nodemon reloads,
// we store the client in the Node global context 'globalThis' if it doesn't already exist.
const globalForPrisma = globalThis;

const prisma = globalForPrisma.prisma || new PrismaClient({
    // Enable query logging during development so we can see the exact SQL generated by Prisma
    log: ['query', 'info', 'warn', 'error'],
});

if (process.env.NODE_ENV !== 'production') {
    globalForPrisma.prisma = prisma;
}

// Export this instance to be imported across all controllers
module.exports = prisma;
